name: orderstate-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jinja2>=3.0.0
  - fonttools>=4.25.0
  - pip
  - pip:
    - flask>=2.0.0,<2.3.0
    - flask-socketio>=5.0.0,<5.4.0
    - eventlet>=0.30.0
    - python-socketio>=5.0.0
    - bidict>=0.21.0
    - werkzeug>=2.0.0,<2.3.0
    - markupsafe>=2.0.0
    - itsdangerous>=2.0.0
    - click>=8.0.0 